version: '3'

services:
  options-ner-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:rw
      - ./training_data.json:/app/training_data.json:ro
      - ./train_model.py:/app/train_model.py:ro
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - MODE=both  # Options: train, serve, both
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Set user to root to avoid permission issues with mounted volumes
    user: root